name: Ui unit tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nix
        run: |
          curl -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix-shell --run "nix --version"
      - name: Build tests
        run: | ## TODO: Future-proof by using nix and just
          mkdir -p ~/.ssh
          echo "${{ secrets.HEE_KEY }}" > ~/.ssh/hee
          chmod 600 ~/.ssh/hee
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/hee
          rm ~/.ssh/hee
          nix-shell --run "just test"
      - name: Exec unit tests
        run: ./tests/testSuite
