name: Ui unit tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build tests
        run: | ## TODO: Future-proof by using nix and just
          mkdir -p ~/.ssh
          echo "${{ secrets.HEE_KEY }}" > ~/.ssh/hee
          chmod 600 ~/.ssh/hee
          ssh-add ~/.ssh/hee
          rm ~/.ssh/hee
          cmake . -DBUILD_TESTS=ON
          make
      - name: Exec unit tests
        run: ./tests/testSuite
